// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: proto/url_cutter.proto

package __

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	URLCutter_GetHandler_FullMethodName       = "/urlcutter.URLCutter/GetHandler"
	URLCutter_GetUserURLs_FullMethodName      = "/urlcutter.URLCutter/GetUserURLs"
	URLCutter_GetStatsHandler_FullMethodName  = "/urlcutter.URLCutter/GetStatsHandler"
	URLCutter_PostHandler_FullMethodName      = "/urlcutter.URLCutter/PostHandler"
	URLCutter_PostBatchHandler_FullMethodName = "/urlcutter.URLCutter/PostBatchHandler"
	URLCutter_DeleteUserURLs_FullMethodName   = "/urlcutter.URLCutter/DeleteUserURLs"
	URLCutter_CheckConnecToDB_FullMethodName  = "/urlcutter.URLCutter/CheckConnecToDB"
)

// URLCutterClient is the client API for URLCutter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type URLCutterClient interface {
	GetHandler(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	GetUserURLs(ctx context.Context, in *GetUserURLSRequest, opts ...grpc.CallOption) (*GetUserURLSResponse, error)
	GetStatsHandler(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetStatsResponse, error)
	PostHandler(ctx context.Context, in *PostRequest, opts ...grpc.CallOption) (*PostResponse, error)
	PostBatchHandler(ctx context.Context, in *PostBatchRequest, opts ...grpc.CallOption) (*PostBatchResponse, error)
	DeleteUserURLs(ctx context.Context, in *DeleteUserURLsRequest, opts ...grpc.CallOption) (*DeleteUserURLsResponse, error)
	CheckConnecToDB(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*CheckConnecToDBResponse, error)
}

type uRLCutterClient struct {
	cc grpc.ClientConnInterface
}

func NewURLCutterClient(cc grpc.ClientConnInterface) URLCutterClient {
	return &uRLCutterClient{cc}
}

func (c *uRLCutterClient) GetHandler(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, URLCutter_GetHandler_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uRLCutterClient) GetUserURLs(ctx context.Context, in *GetUserURLSRequest, opts ...grpc.CallOption) (*GetUserURLSResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserURLSResponse)
	err := c.cc.Invoke(ctx, URLCutter_GetUserURLs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uRLCutterClient) GetStatsHandler(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*GetStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStatsResponse)
	err := c.cc.Invoke(ctx, URLCutter_GetStatsHandler_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uRLCutterClient) PostHandler(ctx context.Context, in *PostRequest, opts ...grpc.CallOption) (*PostResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PostResponse)
	err := c.cc.Invoke(ctx, URLCutter_PostHandler_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uRLCutterClient) PostBatchHandler(ctx context.Context, in *PostBatchRequest, opts ...grpc.CallOption) (*PostBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PostBatchResponse)
	err := c.cc.Invoke(ctx, URLCutter_PostBatchHandler_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uRLCutterClient) DeleteUserURLs(ctx context.Context, in *DeleteUserURLsRequest, opts ...grpc.CallOption) (*DeleteUserURLsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteUserURLsResponse)
	err := c.cc.Invoke(ctx, URLCutter_DeleteUserURLs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *uRLCutterClient) CheckConnecToDB(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*CheckConnecToDBResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckConnecToDBResponse)
	err := c.cc.Invoke(ctx, URLCutter_CheckConnecToDB_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// URLCutterServer is the server API for URLCutter service.
// All implementations must embed UnimplementedURLCutterServer
// for forward compatibility.
type URLCutterServer interface {
	GetHandler(context.Context, *GetRequest) (*GetResponse, error)
	GetUserURLs(context.Context, *GetUserURLSRequest) (*GetUserURLSResponse, error)
	GetStatsHandler(context.Context, *emptypb.Empty) (*GetStatsResponse, error)
	PostHandler(context.Context, *PostRequest) (*PostResponse, error)
	PostBatchHandler(context.Context, *PostBatchRequest) (*PostBatchResponse, error)
	DeleteUserURLs(context.Context, *DeleteUserURLsRequest) (*DeleteUserURLsResponse, error)
	CheckConnecToDB(context.Context, *emptypb.Empty) (*CheckConnecToDBResponse, error)
	mustEmbedUnimplementedURLCutterServer()
}

// UnimplementedURLCutterServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedURLCutterServer struct{}

func (UnimplementedURLCutterServer) GetHandler(context.Context, *GetRequest) (*GetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHandler not implemented")
}
func (UnimplementedURLCutterServer) GetUserURLs(context.Context, *GetUserURLSRequest) (*GetUserURLSResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserURLs not implemented")
}
func (UnimplementedURLCutterServer) GetStatsHandler(context.Context, *emptypb.Empty) (*GetStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStatsHandler not implemented")
}
func (UnimplementedURLCutterServer) PostHandler(context.Context, *PostRequest) (*PostResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PostHandler not implemented")
}
func (UnimplementedURLCutterServer) PostBatchHandler(context.Context, *PostBatchRequest) (*PostBatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PostBatchHandler not implemented")
}
func (UnimplementedURLCutterServer) DeleteUserURLs(context.Context, *DeleteUserURLsRequest) (*DeleteUserURLsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteUserURLs not implemented")
}
func (UnimplementedURLCutterServer) CheckConnecToDB(context.Context, *emptypb.Empty) (*CheckConnecToDBResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckConnecToDB not implemented")
}
func (UnimplementedURLCutterServer) mustEmbedUnimplementedURLCutterServer() {}
func (UnimplementedURLCutterServer) testEmbeddedByValue()                   {}

// UnsafeURLCutterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to URLCutterServer will
// result in compilation errors.
type UnsafeURLCutterServer interface {
	mustEmbedUnimplementedURLCutterServer()
}

func RegisterURLCutterServer(s grpc.ServiceRegistrar, srv URLCutterServer) {
	// If the following call panics, it indicates UnimplementedURLCutterServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&URLCutter_ServiceDesc, srv)
}

func _URLCutter_GetHandler_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(URLCutterServer).GetHandler(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: URLCutter_GetHandler_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(URLCutterServer).GetHandler(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _URLCutter_GetUserURLs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserURLSRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(URLCutterServer).GetUserURLs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: URLCutter_GetUserURLs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(URLCutterServer).GetUserURLs(ctx, req.(*GetUserURLSRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _URLCutter_GetStatsHandler_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(URLCutterServer).GetStatsHandler(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: URLCutter_GetStatsHandler_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(URLCutterServer).GetStatsHandler(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _URLCutter_PostHandler_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(URLCutterServer).PostHandler(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: URLCutter_PostHandler_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(URLCutterServer).PostHandler(ctx, req.(*PostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _URLCutter_PostBatchHandler_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(URLCutterServer).PostBatchHandler(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: URLCutter_PostBatchHandler_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(URLCutterServer).PostBatchHandler(ctx, req.(*PostBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _URLCutter_DeleteUserURLs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserURLsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(URLCutterServer).DeleteUserURLs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: URLCutter_DeleteUserURLs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(URLCutterServer).DeleteUserURLs(ctx, req.(*DeleteUserURLsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _URLCutter_CheckConnecToDB_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(URLCutterServer).CheckConnecToDB(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: URLCutter_CheckConnecToDB_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(URLCutterServer).CheckConnecToDB(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// URLCutter_ServiceDesc is the grpc.ServiceDesc for URLCutter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var URLCutter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "urlcutter.URLCutter",
	HandlerType: (*URLCutterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetHandler",
			Handler:    _URLCutter_GetHandler_Handler,
		},
		{
			MethodName: "GetUserURLs",
			Handler:    _URLCutter_GetUserURLs_Handler,
		},
		{
			MethodName: "GetStatsHandler",
			Handler:    _URLCutter_GetStatsHandler_Handler,
		},
		{
			MethodName: "PostHandler",
			Handler:    _URLCutter_PostHandler_Handler,
		},
		{
			MethodName: "PostBatchHandler",
			Handler:    _URLCutter_PostBatchHandler_Handler,
		},
		{
			MethodName: "DeleteUserURLs",
			Handler:    _URLCutter_DeleteUserURLs_Handler,
		},
		{
			MethodName: "CheckConnecToDB",
			Handler:    _URLCutter_CheckConnecToDB_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/url_cutter.proto",
}
