// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/url_cutter.proto

package __

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortUrl      string                 `protobuf:"bytes,1,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_proto_url_cutter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_url_cutter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_proto_url_cutter_proto_rawDescGZIP(), []int{0}
}

func (x *GetRequest) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OriginalUrl   string                 `protobuf:"bytes,1,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_proto_url_cutter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_url_cutter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_proto_url_cutter_proto_rawDescGZIP(), []int{1}
}

func (x *GetResponse) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

type ShortenURLs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortUrl      string                 `protobuf:"bytes,1,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	OriginalUrl   string                 `protobuf:"bytes,2,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShortenURLs) Reset() {
	*x = ShortenURLs{}
	mi := &file_proto_url_cutter_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShortenURLs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShortenURLs) ProtoMessage() {}

func (x *ShortenURLs) ProtoReflect() protoreflect.Message {
	mi := &file_proto_url_cutter_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShortenURLs.ProtoReflect.Descriptor instead.
func (*ShortenURLs) Descriptor() ([]byte, []int) {
	return file_proto_url_cutter_proto_rawDescGZIP(), []int{2}
}

func (x *ShortenURLs) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

func (x *ShortenURLs) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

type GetUserURLSRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserURLSRequest) Reset() {
	*x = GetUserURLSRequest{}
	mi := &file_proto_url_cutter_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserURLSRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserURLSRequest) ProtoMessage() {}

func (x *GetUserURLSRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_url_cutter_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserURLSRequest.ProtoReflect.Descriptor instead.
func (*GetUserURLSRequest) Descriptor() ([]byte, []int) {
	return file_proto_url_cutter_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserURLSRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetUserURLSResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OriginalUrls  []*ShortenURLs         `protobuf:"bytes,1,rep,name=original_urls,json=originalUrls,proto3" json:"original_urls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserURLSResponse) Reset() {
	*x = GetUserURLSResponse{}
	mi := &file_proto_url_cutter_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserURLSResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserURLSResponse) ProtoMessage() {}

func (x *GetUserURLSResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_url_cutter_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserURLSResponse.ProtoReflect.Descriptor instead.
func (*GetUserURLSResponse) Descriptor() ([]byte, []int) {
	return file_proto_url_cutter_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserURLSResponse) GetOriginalUrls() []*ShortenURLs {
	if x != nil {
		return x.OriginalUrls
	}
	return nil
}

type GetStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsRequest) Reset() {
	*x = GetStatsRequest{}
	mi := &file_proto_url_cutter_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsRequest) ProtoMessage() {}

func (x *GetStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_url_cutter_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsRequest.ProtoReflect.Descriptor instead.
func (*GetStatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_url_cutter_proto_rawDescGZIP(), []int{5}
}

type GetStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalUsers    int64                  `protobuf:"varint,1,opt,name=total_users,json=totalUsers,proto3" json:"total_users,omitempty"`
	TotalUrls     int64                  `protobuf:"varint,2,opt,name=total_urls,json=totalUrls,proto3" json:"total_urls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsResponse) Reset() {
	*x = GetStatsResponse{}
	mi := &file_proto_url_cutter_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsResponse) ProtoMessage() {}

func (x *GetStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_url_cutter_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsResponse.ProtoReflect.Descriptor instead.
func (*GetStatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_url_cutter_proto_rawDescGZIP(), []int{6}
}

func (x *GetStatsResponse) GetTotalUsers() int64 {
	if x != nil {
		return x.TotalUsers
	}
	return 0
}

func (x *GetStatsResponse) GetTotalUrls() int64 {
	if x != nil {
		return x.TotalUrls
	}
	return 0
}

type PostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OriginalUrl   string                 `protobuf:"bytes,2,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostRequest) Reset() {
	*x = PostRequest{}
	mi := &file_proto_url_cutter_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostRequest) ProtoMessage() {}

func (x *PostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_url_cutter_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostRequest.ProtoReflect.Descriptor instead.
func (*PostRequest) Descriptor() ([]byte, []int) {
	return file_proto_url_cutter_proto_rawDescGZIP(), []int{7}
}

func (x *PostRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PostRequest) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

type PostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShortUrl      string                 `protobuf:"bytes,1,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostResponse) Reset() {
	*x = PostResponse{}
	mi := &file_proto_url_cutter_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostResponse) ProtoMessage() {}

func (x *PostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_url_cutter_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostResponse.ProtoReflect.Descriptor instead.
func (*PostResponse) Descriptor() ([]byte, []int) {
	return file_proto_url_cutter_proto_rawDescGZIP(), []int{8}
}

func (x *PostResponse) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

type BatchRequestItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        int64                  `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	OriginalUrl   string                 `protobuf:"bytes,2,opt,name=original_url,json=originalUrl,proto3" json:"original_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchRequestItem) Reset() {
	*x = BatchRequestItem{}
	mi := &file_proto_url_cutter_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchRequestItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchRequestItem) ProtoMessage() {}

func (x *BatchRequestItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_url_cutter_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchRequestItem.ProtoReflect.Descriptor instead.
func (*BatchRequestItem) Descriptor() ([]byte, []int) {
	return file_proto_url_cutter_proto_rawDescGZIP(), []int{9}
}

func (x *BatchRequestItem) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *BatchRequestItem) GetOriginalUrl() string {
	if x != nil {
		return x.OriginalUrl
	}
	return ""
}

type BatchResponseItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        int64                  `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	ShortUrl      string                 `protobuf:"bytes,2,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchResponseItem) Reset() {
	*x = BatchResponseItem{}
	mi := &file_proto_url_cutter_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchResponseItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchResponseItem) ProtoMessage() {}

func (x *BatchResponseItem) ProtoReflect() protoreflect.Message {
	mi := &file_proto_url_cutter_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchResponseItem.ProtoReflect.Descriptor instead.
func (*BatchResponseItem) Descriptor() ([]byte, []int) {
	return file_proto_url_cutter_proto_rawDescGZIP(), []int{10}
}

func (x *BatchResponseItem) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *BatchResponseItem) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

type PostBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        int64                  `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	Items         []*BatchRequestItem    `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostBatchRequest) Reset() {
	*x = PostBatchRequest{}
	mi := &file_proto_url_cutter_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostBatchRequest) ProtoMessage() {}

func (x *PostBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_url_cutter_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostBatchRequest.ProtoReflect.Descriptor instead.
func (*PostBatchRequest) Descriptor() ([]byte, []int) {
	return file_proto_url_cutter_proto_rawDescGZIP(), []int{11}
}

func (x *PostBatchRequest) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *PostBatchRequest) GetItems() []*BatchRequestItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type PostBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*BatchResponseItem   `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostBatchResponse) Reset() {
	*x = PostBatchResponse{}
	mi := &file_proto_url_cutter_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostBatchResponse) ProtoMessage() {}

func (x *PostBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_url_cutter_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostBatchResponse.ProtoReflect.Descriptor instead.
func (*PostBatchResponse) Descriptor() ([]byte, []int) {
	return file_proto_url_cutter_proto_rawDescGZIP(), []int{12}
}

func (x *PostBatchResponse) GetItems() []*BatchResponseItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type DeleteUserURLsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OriginalUrls  []string               `protobuf:"bytes,1,rep,name=original_urls,json=originalUrls,proto3" json:"original_urls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserURLsRequest) Reset() {
	*x = DeleteUserURLsRequest{}
	mi := &file_proto_url_cutter_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserURLsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserURLsRequest) ProtoMessage() {}

func (x *DeleteUserURLsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_url_cutter_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserURLsRequest.ProtoReflect.Descriptor instead.
func (*DeleteUserURLsRequest) Descriptor() ([]byte, []int) {
	return file_proto_url_cutter_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteUserURLsRequest) GetOriginalUrls() []string {
	if x != nil {
		return x.OriginalUrls
	}
	return nil
}

type DeleteUserURLsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteUserURLsResponse) Reset() {
	*x = DeleteUserURLsResponse{}
	mi := &file_proto_url_cutter_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteUserURLsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteUserURLsResponse) ProtoMessage() {}

func (x *DeleteUserURLsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_url_cutter_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteUserURLsResponse.ProtoReflect.Descriptor instead.
func (*DeleteUserURLsResponse) Descriptor() ([]byte, []int) {
	return file_proto_url_cutter_proto_rawDescGZIP(), []int{14}
}

type CheckConnecToDBResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckConnecToDBResponse) Reset() {
	*x = CheckConnecToDBResponse{}
	mi := &file_proto_url_cutter_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckConnecToDBResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckConnecToDBResponse) ProtoMessage() {}

func (x *CheckConnecToDBResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_url_cutter_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckConnecToDBResponse.ProtoReflect.Descriptor instead.
func (*CheckConnecToDBResponse) Descriptor() ([]byte, []int) {
	return file_proto_url_cutter_proto_rawDescGZIP(), []int{15}
}

var File_proto_url_cutter_proto protoreflect.FileDescriptor

const file_proto_url_cutter_proto_rawDesc = "" +
	"\n" +
	"\x16proto/url_cutter.proto\x12\turlcutter\x1a\x1bgoogle/protobuf/empty.proto\")\n" +
	"\n" +
	"GetRequest\x12\x1b\n" +
	"\tshort_url\x18\x01 \x01(\tR\bshortUrl\"0\n" +
	"\vGetResponse\x12!\n" +
	"\foriginal_url\x18\x01 \x01(\tR\voriginalUrl\"M\n" +
	"\vShortenURLs\x12\x1b\n" +
	"\tshort_url\x18\x01 \x01(\tR\bshortUrl\x12!\n" +
	"\foriginal_url\x18\x02 \x01(\tR\voriginalUrl\"-\n" +
	"\x12GetUserURLSRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"R\n" +
	"\x13GetUserURLSResponse\x12;\n" +
	"\roriginal_urls\x18\x01 \x03(\v2\x16.urlcutter.ShortenURLsR\foriginalUrls\"\x11\n" +
	"\x0fGetStatsRequest\"R\n" +
	"\x10GetStatsResponse\x12\x1f\n" +
	"\vtotal_users\x18\x01 \x01(\x03R\n" +
	"totalUsers\x12\x1d\n" +
	"\n" +
	"total_urls\x18\x02 \x01(\x03R\ttotalUrls\"I\n" +
	"\vPostRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12!\n" +
	"\foriginal_url\x18\x02 \x01(\tR\voriginalUrl\"+\n" +
	"\fPostResponse\x12\x1b\n" +
	"\tshort_url\x18\x01 \x01(\tR\bshortUrl\"M\n" +
	"\x10BatchRequestItem\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\x03R\x06userID\x12!\n" +
	"\foriginal_url\x18\x02 \x01(\tR\voriginalUrl\"H\n" +
	"\x11BatchResponseItem\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\x03R\x06userID\x12\x1b\n" +
	"\tshort_url\x18\x02 \x01(\tR\bshortUrl\"]\n" +
	"\x10PostBatchRequest\x12\x16\n" +
	"\x06userID\x18\x01 \x01(\x03R\x06userID\x121\n" +
	"\x05items\x18\x02 \x03(\v2\x1b.urlcutter.BatchRequestItemR\x05items\"G\n" +
	"\x11PostBatchResponse\x122\n" +
	"\x05items\x18\x01 \x03(\v2\x1c.urlcutter.BatchResponseItemR\x05items\"<\n" +
	"\x15DeleteUserURLsRequest\x12#\n" +
	"\roriginal_urls\x18\x01 \x03(\tR\foriginalUrls\"\x18\n" +
	"\x16DeleteUserURLsResponse\"\x19\n" +
	"\x17CheckConnecToDBResponse2\x97\x04\n" +
	"\tURLCutter\x12;\n" +
	"\n" +
	"GetHandler\x12\x15.urlcutter.GetRequest\x1a\x16.urlcutter.GetResponse\x12L\n" +
	"\vGetUserURLs\x12\x1d.urlcutter.GetUserURLSRequest\x1a\x1e.urlcutter.GetUserURLSResponse\x12J\n" +
	"\x0fGetStatsHandler\x12\x1a.urlcutter.GetStatsRequest\x1a\x1b.urlcutter.GetStatsResponse\x12>\n" +
	"\vPostHandler\x12\x16.urlcutter.PostRequest\x1a\x17.urlcutter.PostResponse\x12M\n" +
	"\x10PostBatchHandler\x12\x1b.urlcutter.PostBatchRequest\x1a\x1c.urlcutter.PostBatchResponse\x12U\n" +
	"\x0eDeleteUserURLs\x12 .urlcutter.DeleteUserURLsRequest\x1a!.urlcutter.DeleteUserURLsResponse\x12M\n" +
	"\x0fCheckConnecToDB\x12\x16.google.protobuf.Empty\x1a\".urlcutter.CheckConnecToDBResponseB\x04Z\x02.;b\x06proto3"

var (
	file_proto_url_cutter_proto_rawDescOnce sync.Once
	file_proto_url_cutter_proto_rawDescData []byte
)

func file_proto_url_cutter_proto_rawDescGZIP() []byte {
	file_proto_url_cutter_proto_rawDescOnce.Do(func() {
		file_proto_url_cutter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_url_cutter_proto_rawDesc), len(file_proto_url_cutter_proto_rawDesc)))
	})
	return file_proto_url_cutter_proto_rawDescData
}

var file_proto_url_cutter_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_proto_url_cutter_proto_goTypes = []any{
	(*GetRequest)(nil),              // 0: urlcutter.GetRequest
	(*GetResponse)(nil),             // 1: urlcutter.GetResponse
	(*ShortenURLs)(nil),             // 2: urlcutter.ShortenURLs
	(*GetUserURLSRequest)(nil),      // 3: urlcutter.GetUserURLSRequest
	(*GetUserURLSResponse)(nil),     // 4: urlcutter.GetUserURLSResponse
	(*GetStatsRequest)(nil),         // 5: urlcutter.GetStatsRequest
	(*GetStatsResponse)(nil),        // 6: urlcutter.GetStatsResponse
	(*PostRequest)(nil),             // 7: urlcutter.PostRequest
	(*PostResponse)(nil),            // 8: urlcutter.PostResponse
	(*BatchRequestItem)(nil),        // 9: urlcutter.BatchRequestItem
	(*BatchResponseItem)(nil),       // 10: urlcutter.BatchResponseItem
	(*PostBatchRequest)(nil),        // 11: urlcutter.PostBatchRequest
	(*PostBatchResponse)(nil),       // 12: urlcutter.PostBatchResponse
	(*DeleteUserURLsRequest)(nil),   // 13: urlcutter.DeleteUserURLsRequest
	(*DeleteUserURLsResponse)(nil),  // 14: urlcutter.DeleteUserURLsResponse
	(*CheckConnecToDBResponse)(nil), // 15: urlcutter.CheckConnecToDBResponse
	(*emptypb.Empty)(nil),           // 16: google.protobuf.Empty
}
var file_proto_url_cutter_proto_depIdxs = []int32{
	2,  // 0: urlcutter.GetUserURLSResponse.original_urls:type_name -> urlcutter.ShortenURLs
	9,  // 1: urlcutter.PostBatchRequest.items:type_name -> urlcutter.BatchRequestItem
	10, // 2: urlcutter.PostBatchResponse.items:type_name -> urlcutter.BatchResponseItem
	0,  // 3: urlcutter.URLCutter.GetHandler:input_type -> urlcutter.GetRequest
	3,  // 4: urlcutter.URLCutter.GetUserURLs:input_type -> urlcutter.GetUserURLSRequest
	5,  // 5: urlcutter.URLCutter.GetStatsHandler:input_type -> urlcutter.GetStatsRequest
	7,  // 6: urlcutter.URLCutter.PostHandler:input_type -> urlcutter.PostRequest
	11, // 7: urlcutter.URLCutter.PostBatchHandler:input_type -> urlcutter.PostBatchRequest
	13, // 8: urlcutter.URLCutter.DeleteUserURLs:input_type -> urlcutter.DeleteUserURLsRequest
	16, // 9: urlcutter.URLCutter.CheckConnecToDB:input_type -> google.protobuf.Empty
	1,  // 10: urlcutter.URLCutter.GetHandler:output_type -> urlcutter.GetResponse
	4,  // 11: urlcutter.URLCutter.GetUserURLs:output_type -> urlcutter.GetUserURLSResponse
	6,  // 12: urlcutter.URLCutter.GetStatsHandler:output_type -> urlcutter.GetStatsResponse
	8,  // 13: urlcutter.URLCutter.PostHandler:output_type -> urlcutter.PostResponse
	12, // 14: urlcutter.URLCutter.PostBatchHandler:output_type -> urlcutter.PostBatchResponse
	14, // 15: urlcutter.URLCutter.DeleteUserURLs:output_type -> urlcutter.DeleteUserURLsResponse
	15, // 16: urlcutter.URLCutter.CheckConnecToDB:output_type -> urlcutter.CheckConnecToDBResponse
	10, // [10:17] is the sub-list for method output_type
	3,  // [3:10] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_url_cutter_proto_init() }
func file_proto_url_cutter_proto_init() {
	if File_proto_url_cutter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_url_cutter_proto_rawDesc), len(file_proto_url_cutter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_url_cutter_proto_goTypes,
		DependencyIndexes: file_proto_url_cutter_proto_depIdxs,
		MessageInfos:      file_proto_url_cutter_proto_msgTypes,
	}.Build()
	File_proto_url_cutter_proto = out.File
	file_proto_url_cutter_proto_goTypes = nil
	file_proto_url_cutter_proto_depIdxs = nil
}
